version: '3.7'
services:
  register-runner:
    deploy:
      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME:?err}
    restart: 'no'
    depends_on:
      - gitlab-ce
    image: gitlab/gitlab-runner:latest
    volumes:
      - ${VOLUME_PATH:?err}/gitlab-runner-config:/etc/gitlab-runner:Z
    command:
      - register
      - --non-interactive
      - --locked=false
      - --docker-privileged
      - --name=${NAME_RUNNER:-Veone Runner}
      - --executor=docker
      - --docker-image=docker:20.10.5
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL:?err}
      - REGISTRATION_TOKEN=${GITLAB_TOKEN:?err}
    
  gitlab-runner:
    deploy:
      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME:?err}
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner
    depends_on:
      - register-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_PATH:?err}/gitlab-runner-config:/etc/gitlab-runner:Z
    environment:
      - CONFIG_FILE=/etc/gitlab-runner/config.toml


