version: '3.7'
services:
  register-runner:
    deploy:
      placement:
        constraints:
          - node.hostname == minio2.veone.free.ci
    restart: 'no'
    image: gitlab/gitlab-runner:latest
    volumes:
    - /data/gitlab-runner-config:/etc/gitlab-runner:Z
    command:
    - register
    - --non-interactive
    - --locked=false
    - --docker-privileged
    - --name=Runner Dev
    - --executor=docker
    - --docker-image=docker:20.10.5
    - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    environment:
    - CI_SERVER_URL=https://gitlab.veone.free.ci/
    - REGISTRATION_TOKEN=ZdBccTVWrCGeUDJHsDc1
    networks:
      - ty
    
  gitlab-runner:
    deploy:
      placement:
        constraints:
          - node.hostname == minio2.veone.free.ci
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab-runner
    depends_on:
      - register-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/gitlab-runner-config:/etc/gitlab-runner:Z
    environment:
      - CONFIG_FILE=/etc/gitlab-runner/config.toml
    networks:
      - ty
      
networks:
  ty:
#    external: true
