version: '3.8'

services:
  traefik:
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@${DOMAIN:?err}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    image: traefik:v2.2
    ports:
      - 80:80
      - 443:443
      - ${TRAEFIK_DASHBOARD_PUBLISHED_PORT:-8080}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/docker/letsencrypt:/letsencrypt"

  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.33.0
    restart: always
    ports:
      - 8083:8083
      - 8084:8084
    volumes:
      - /nexus-data:/nexus-data
    labels:
      - traefik.port=8081
      - traefik.http.routers.nexus.rule=Host(`nexus.${DOMAIN:?err}`)
      - traefik.enable=true
      - traefik.http.routers.nexus.entrypoints=https
      - traefik.http.routers.nexus.tls=true
      - traefik.http.routers.nexus.tls.certresolver=letsencrypt
